'use client'
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Provider } from "react-redux";
import store from "@/store/store";

import TopNav from "../components/TopNav";

const inter = Inter({ subsets: ["latin"] });

import client from '@/lib/apolloClient.config';

import { ApolloProvider } from '@apollo/client';

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <Provider store={store}>

    <ApolloProvider client={client}>
    <html lang="en">

      <body className={inter.className}>
        <TopNav />
        {children}
        </body>
    </html>
    </ApolloProvider>
    </Provider>
  );
}
