"use client";
import {
  ClerkProvider,
  SignInButton,
  SignedIn,
  SignedOut,
  UserButton,
} from "@clerk/nextjs";

import { Inter } from "next/font/google";
import "./globals.css";
import { Provider } from "react-redux";
import store from "@/store/store";

import TopNav from "../components/TopNav";

const inter = Inter({ subsets: ["latin"] });

import client from "@/lib/apolloClient.config";

import { ApolloProvider } from "@apollo/client";
import { Toaster } from "@/components/ui/toaster";

import MyApolloProvider from "@/components/apolloProvider";

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <Provider store={store}>
        {/* <MyApolloProvider><></></MyApolloProvider> */}
        {/* <ApolloProvider client={client}> */}
        <MyApolloProvider>

        <html lang="en">
          <body className={inter.className}>
            <TopNav />
            {children}
            <Toaster />
          </body>
        </html>
        </MyApolloProvider>
        {/* </ApolloProvider> */}
      </Provider>
    </ClerkProvider>
  );
}
